[package]
name = "explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
serde = { version = "1.0.203", features = ["derive"] }
surrealdb = "1.5.3"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
